import { transform } from "@svgr/core";
import jsx from "@svgr/plugin-jsx";
import svgo from "@svgr/plugin-svgo";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readFile } from "node:fs/promises";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const iconsDir = path.join(rootDir, "icons");
const outputDir = path.join(rootDir, "src", "icons");

function toPascalCase(filename) {
  const base = filename.replace(/\.svg$/i, "");
  return base
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}

function toExportName(filename) {
  return `${toPascalCase(filename)}Icon`;
}

const svgrConfig = {
  plugins: [svgo, jsx],
  typescript: true,
  ref: false,
  expandProps: "end",
  jsxRuntime: "automatic",
  svgoConfig: {
    plugins: [
      {
        name: "preset-default",
        params: {
          overrides: {
            removeViewBox: false,
          },
        },
      },
      "removeDimensions",
    ],
  },
};

async function buildIconComponent(filename) {
  const svgPath = path.join(iconsDir, filename);
  const svgSource = await readFile(svgPath, "utf8");
  const componentName = toExportName(filename);
  const propsTypeName = `${toPascalCase(filename)}IconProps`;

  const componentSource = await transform(
    svgSource,
    {
      ...svgrConfig,
      componentName: "Svg",
      template: (variables, { tpl }) => tpl`
import { createIcon, type IconProps } from "../createIcon";
import type { SVGProps } from "react";
const Svg = (props: SVGProps<SVGSVGElement>) => (${variables.jsx});
export const ${componentName} = createIcon("${componentName}", Svg);
export type ${propsTypeName} = IconProps;
`,
    },
    { componentName: "Svg" }
  );

  const outputPath = path.join(outputDir, `${filename.replace(/\.svg$/i, "")}.tsx`);
  const normalizedSource = componentSource.replaceAll(
    'writingMode: "lr-tb"',
    'writingMode: "horizontal-tb"'
  );
  await writeFile(outputPath, normalizedSource, "utf8");

  return componentName;
}

async function main() {
  await mkdir(outputDir, { recursive: true });

  const svgFiles = (await readdir(iconsDir))
    .filter((file) => file.toLowerCase().endsWith(".svg"))
    .sort((a, b) => a.localeCompare(b));

  const exports = [];

  for (const file of svgFiles) {
    const exportName = await buildIconComponent(file);
    exports.push(exportName);
    console.log(`Generated ${exportName} from ${file}`);
  }

  const indexLines = [
    "// Generated by scripts/build-icons.mjs — do not edit manually.",
    'export { createIcon, type IconProps } from "./createIcon";',
    "",
  ];

  for (const file of svgFiles) {
    const stem = file.replace(/\.svg$/i, "");
    const exportName = toExportName(file);
    indexLines.push(`export { ${exportName} } from "./icons/${stem}";`);
  }

  await writeFile(path.join(rootDir, "src", "index.ts"), `${indexLines.join("\n")}\n`, "utf8");

  const manifest = svgFiles.map((file) => ({
    file,
    exportName: toExportName(file),
  }));

  await writeFile(
    path.join(rootDir, "src", "icons-manifest.json"),
    `${JSON.stringify(manifest, null, 2)}\n`,
    "utf8"
  );

  console.log(`\nBuilt ${exports.length} icon components.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
