// Generated by scripts/build-icons.mjs — do not edit manually.
export { createIcon, type IconProps } from "./createIcon";

export { Alu41Icon } from "./icons/alu-41";
export { BiodegradableIcon } from "./icons/Biodegradable";
export { EkobulpackIcon } from "./icons/ekobulpack";
export { Fe40Icon } from "./icons/fe-40";
export { Gl70Icon } from "./icons/gl-70";
export { Gl71Icon } from "./icons/gl-71";
export { Gl72Icon } from "./icons/gl-72";
export { GreenDotIcon } from "./icons/green-dot";
export { GrunePunktIcon } from "./icons/grune-punkt";
export { Hdpe2Icon } from "./icons/hdpe-2";
export { Ldpe4Icon } from "./icons/ldpe-4";
export { MobiusLoopIcon } from "./icons/mobius-loop";
export { Other7Icon } from "./icons/other-7";
export { Pap20Icon } from "./icons/pap-20";
export { Pap21Icon } from "./icons/pap-21";
export { Pap22Icon } from "./icons/pap-22";
export { Pet1Icon } from "./icons/pet-1";
export { Pp5Icon } from "./icons/pp-5";
export { Ps6Icon } from "./icons/ps-6";
export { Pvc3Icon } from "./icons/pvc-3";
export { TidymanIcon } from "./icons/tidyman";
export { TrimanIcon } from "./icons/triman";
